Repository viniciusferrao/cloysterhpc, pull requests merged in 2024-08, with the labels that each got.

#60 Implement Doxygen in (almost) all the headers
  include/cloysterhpc/NFS.h
  include/cloysterhpc/answerfile.h
  include/cloysterhpc/cluster.h
  include/cloysterhpc/connection.h
  include/cloysterhpc/diskImage.h
  include/cloysterhpc/functions.h
  include/cloysterhpc/inifile.h
  include/cloysterhpc/network.h
  include/cloysterhpc/node.h
  include/cloysterhpc/ofed.h
  include/cloysterhpc/os.h
  include/cloysterhpc/queuesystem/slurm.h
  include/cloysterhpc/server.h
  include/cloysterhpc/services/bmc.h
  include/cloysterhpc/services/locale.h
  include/cloysterhpc/services/log.h
  include/cloysterhpc/services/shell.h
  include/cloysterhpc/services/timezone.h
  include/cloysterhpc/services/xcat.h
Labels: documentation

#66 Disable sanitizers on release builds
  cmake/Hardening.cmake
  cmake/Sanitizers.cmake
Labels: bug

#68 [CLOYSTER-116] Implement Ansible + Vagrant to run Cloyster
  ansible/README.md
  ansible/Vagrantfile
  ansible/ansible.cfg
  ansible/roles/cloyster_setup/provision/rhel8-based.yml
  ansible/roles/cloyster_setup/provision/rhel8.yml
  ansible/roles/cloyster_setup/provision/rhel9-based.yml
  ansible/roles/cloyster_setup/provision/rhel9.yml
  ansible/roles/cloyster_setup/tasks/cleanup.yml
  ansible/roles/cloyster_setup/tasks/create_vm.yml
  ansible/roles/cloyster_setup/tasks/install_plugin.yml
  ansible/roles/cloyster_setup/tasks/main.yml
  ansible/roles/cloyster_setup/tasks/run_cloyster.yml
  ansible/roles/cloyster_setup/templates/answerfile.j2
  ansible/roles/cloyster_setup/vars/machines.yml
  ansible/roles/cloyster_setup/vars/main.yml
  ansible/setup.yml
  vagrant/README.md
  vagrant/Vagrantfile
  vagrant/include/alma-8.answerfile.ini
  vagrant/include/alma-9.answerfile.ini
  vagrant/include/oracle-8.answerfile.ini
  vagrant/include/oracle-9.answerfile.ini
  vagrant/include/rhel-8.answerfile.ini
  vagrant/include/rhel-9.answerfile.ini
  vagrant/include/rocky-9.answerfile.ini
  vagrant/provision/rhel-8-based.sh
  vagrant/provision/rhel-8.sh
  vagrant/provision/rhel-9-based.sh
  vagrant/provision/rhel-9.sh
  vagrant/setupVagrant.sh
Labels: enhancement

#69 [CLOYSTER-109] Implement service network
  example.answerfile.ini
  include/cloysterhpc/answerfile.h
  src/answerfile.cpp
  src/cluster.cpp
Labels: enhancement
